name: Stale Issues and PRs

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Issues configuration
          days-before-issue-stale: 60
          days-before-issue-close: 14
          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,security,bug,enhancement,help-wanted'
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed in 14 days if no further activity occurs.
            Thank you for your contributions.
          close-issue-message: >
            This issue was automatically closed because it has been stale for 14 days
            with no activity. Please reopen if this is still relevant.
          
          # Pull requests configuration
          days-before-pr-stale: 30
          days-before-pr-close: 14
          stale-pr-label: 'stale'
          exempt-pr-labels: 'pinned,security,work-in-progress'
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had
            recent activity. It will be closed in 14 days if no further activity occurs.
            Thank you for your contributions.
          close-pr-message: >
            This pull request was automatically closed because it has been stale for 14 days
            with no activity. Please reopen if you'd like to continue working on this.
          
          # General configuration
          operations-per-run: 100
          remove-stale-when-updated: true
          ascending: false

